
server:
  port: 7000
  
#spring:
#  datasource:
#    url: jdbc:h2:./devdb
#    username: sa
#  jpa:
#    hibernate:
#      ddl-auto: update

spring:
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
            
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
  profiles:
    active:
    - dev
  servlet:
    multipart:
      max-file-size: 10MB
hoaxify:
  upload-path: picture-storage
--- #Yeni profiller oluşturma ---ile oluşturulur
spring:
  profiles: production
hoaxify:
  upload-path: storage-production
---
spring:
  profiles: dev
hoaxify:
  upload-path: storage-dev  

  
